-- =========================
-- HR Docs Desktop - Schema + RLS (Updated)
-- Fixes:
--  - Soft delete via is_active (clients, workers)
--  - Linter ERROR: enable RLS on incident_types with read policy
--  - Linter WARN: wrap auth.uid() as (select auth.uid())
-- UUIDs generated by Postgres
-- =========================

create extension if not exists pgcrypto;

-- =========================
-- TABLES
-- =========================

-- CLIENTS
create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null,

  name text not null,
  legal_id text not null,
  description text null,

  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_clients_owner_user_id on public.clients(owner_user_id);
create unique index if not exists uq_clients_owner_legal_id
  on public.clients(owner_user_id, legal_id);

-- WORKERS
create table if not exists public.workers (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null,

  client_id uuid not null references public.clients(id) on delete cascade,

  full_name text not null,
  national_id text not null,

  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_workers_owner_user_id on public.workers(owner_user_id);
create index if not exists idx_workers_client_id on public.workers(client_id);
create unique index if not exists uq_workers_owner_national_id
  on public.workers(owner_user_id, national_id);

-- INCIDENT TYPES (static)
create table if not exists public.incident_types (
  id smallint primary key,
  code text not null unique,
  name text not null
);

insert into public.incident_types (id, code, name)
values
  (1, 'ABSENCE', 'Absence'),
  (2, 'LATE_ARRIVAL', 'Late Arrival'),
  (3, 'JOB_ABANDONMENT', 'Job Abandonment')
on conflict (id) do nothing;

-- INCIDENTS
create table if not exists public.incidents (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null,

  worker_id uuid not null references public.workers(id) on delete cascade,
  incident_type_id smallint not null references public.incident_types(id),

  incident_date date not null,
  observations text null,
  manual_handling boolean not null default false,

  created_at timestamptz not null default now()
);

create index if not exists idx_incidents_owner_user_id on public.incidents(owner_user_id);
create index if not exists idx_incidents_worker_id on public.incidents(worker_id);
create index if not exists idx_incidents_date on public.incidents(incident_date);
create index if not exists idx_incidents_type on public.incidents(incident_type_id);

-- DOCUMENT TEMPLATES
create table if not exists public.document_templates (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null,

  client_id uuid not null references public.clients(id) on delete cascade,

  template_key text not null,
  storage_path text not null,

  version integer not null default 1,
  is_active boolean not null default true,

  created_at timestamptz not null default now()
);

create index if not exists idx_templates_owner_user_id on public.document_templates(owner_user_id);
create index if not exists idx_templates_client_id on public.document_templates(client_id);

create unique index if not exists uq_templates_owner_client_key_active
  on public.document_templates(owner_user_id, client_id, template_key, is_active)
  where is_active = true;

-- =========================
-- If tables already existed from your previous run, ensure soft-delete columns exist
-- =========================
alter table public.clients add column if not exists is_active boolean not null default true;
alter table public.workers add column if not exists is_active boolean not null default true;

-- =========================
-- RLS ENABLE
-- =========================
alter table public.clients enable row level security;
alter table public.workers enable row level security;
alter table public.incidents enable row level security;
alter table public.document_templates enable row level security;

-- Fix linter ERROR: enable RLS for incident_types too
alter table public.incident_types enable row level security;

-- =========================
-- RLS POLICIES (use (select auth.uid()) to avoid initplan warnings)
-- =========================

-- CLIENTS
drop policy if exists clients_select_own on public.clients;
create policy clients_select_own
on public.clients for select
using (
  owner_user_id = (select auth.uid())
  and is_active = true
);

drop policy if exists clients_insert_own on public.clients;
create policy clients_insert_own
on public.clients for insert
with check (owner_user_id = (select auth.uid()));

drop policy if exists clients_update_own on public.clients;
create policy clients_update_own
on public.clients for update
using (owner_user_id = (select auth.uid()))
with check (owner_user_id = (select auth.uid()));

-- IMPORTANT: soft delete means you usually shouldn't delete rows.
-- You can keep delete enabled or disable it.
-- Recommended: disable delete by NOT creating a delete policy.
drop policy if exists clients_delete_own on public.clients;

-- WORKERS
drop policy if exists workers_select_own on public.workers;
create policy workers_select_own
on public.workers for select
using (
  owner_user_id = (select auth.uid())
  and is_active = true
);

drop policy if exists workers_insert_own on public.workers;
create policy workers_insert_own
on public.workers for insert
with check (owner_user_id = (select auth.uid()));

drop policy if exists workers_update_own on public.workers;
create policy workers_update_own
on public.workers for update
using (owner_user_id = (select auth.uid()))
with check (owner_user_id = (select auth.uid()));

drop policy if exists workers_delete_own on public.workers;

-- INCIDENTS (keep visible even if worker/client later becomes inactive)
drop policy if exists incidents_select_own on public.incidents;
create policy incidents_select_own
on public.incidents for select
using (owner_user_id = (select auth.uid()));

drop policy if exists incidents_insert_own on public.incidents;
create policy incidents_insert_own
on public.incidents for insert
with check (owner_user_id = (select auth.uid()));

drop policy if exists incidents_update_own on public.incidents;
create policy incidents_update_own
on public.incidents for update
using (owner_user_id = (select auth.uid()))
with check (owner_user_id = (select auth.uid()));

drop policy if exists incidents_delete_own on public.incidents;
create policy incidents_delete_own
on public.incidents for delete
using (owner_user_id = (select auth.uid()));

-- DOCUMENT TEMPLATES
drop policy if exists templates_select_own on public.document_templates;
create policy templates_select_own
on public.document_templates for select
using (
  owner_user_id = (select auth.uid())
  and is_active = true
);

drop policy if exists templates_insert_own on public.document_templates;
create policy templates_insert_own
on public.document_templates for insert
with check (owner_user_id = (select auth.uid()));

drop policy if exists templates_update_own on public.document_templates;
create policy templates_update_own
on public.document_templates for update
using (owner_user_id = (select auth.uid()))
with check (owner_user_id = (select auth.uid()));

drop policy if exists templates_delete_own on public.document_templates;
create policy templates_delete_own
on public.document_templates for delete
using (owner_user_id = (select auth.uid()));

-- INCIDENT TYPES: allow everyone (logged-in) to read
drop policy if exists incident_types_select_all on public.incident_types;
create policy incident_types_select_all
on public.incident_types for select
using (true);

-- No insert/update/delete policies for incident_types = effectively read-only for normal users